name: 95prd --- sa-bcm-wfmforms-ui ---
on:
  workflow_dispatch:
    branches:
      - main # Aqui va la rama
jobs:
  deploy:
    runs-on: [self-hosted, linux, test-deploy]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_95}} # Clave privada

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_95}} 	# Nombre de host
          username: ${{secrets.SSH_USERNAME_95}} # nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_95}} # Clave privada
          script: |
            echo "### Path servidor 95 ###"
            cd /adsaenv/adsa/app/adsaweb
            pwd
            ls -lrt 
            echo "### Respaldo de la carpeta sa-bcm-wfmforms-ui ###"
            mv sa-bcm-wfmforms-ui /adsaenv/adsa/app/adsawebsa-bcm-wfmforms-ui_$(date +'%Y%m%d-%H%M')
            ls -lrt 
            echo '### Clonar el repositorio sa-bcm-wfmforms-ui ###'
            git clone -b main https://${{secrets.GH_ACCESS_KEY}}@github.com/jeacor/sa-bcm-wfmforms-ui.git
            echo '### Repositorio clonado ###' 
            ls -lrt
            sleep 20
            echo '### Detener y eliminar el Contenedor sa-bcm-wfmforms-ui ###'
            docker ps
            docker stop bcm-wfmforms-ui-container
            sleep 20
            docker rm bcm-wfmforms-ui-container
            echo '### Eliminando la imagen... ###'
            docker images
            sleep 40
            docker rmi bcm-wfmforms-ui
            docker images
            echo '### Ejecutando el Build y Deploy ###'
            cd  /adsaenv/adsa/app/adsaweb/sa-bcm-wfmforms-ui
            ls -lrt
            docker build -t bcm-wfmforms-ui .
            sleep 20
            docker run -d -p 5103:8080 -v dataprotection-keys:/root/.aspnet/DataProtection-Keys --name  bcm-wfmforms-ui-container bcm-wfmforms-ui
            sleep 20
            echo '### Contenedores corriendo ###'
            docker ps -a
            echo '### fin del workflow ###'
