name: 172 --- sa-bcm-content-ui 172 ---
on:
  workflow_dispatch:
    branches:
      - main # Aqui va la rama
jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_172}} # Clave privada

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_172}} 	# Nombre de host
          username: ${{secrets.SSH_USERNAME_172}} # nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_172}} # Clave privada
          script: |
            echo "###### Path servidor 172 ######"
            cd /home/GIT
            pwd
            ls -lrt 
            echo "###### Respaldo de la carpeta sa-bcm-content-ui ######"
            mv sa-bcm-content-ui /home/GIT/sa-bcm-content-ui_$(date +'%Y%m%d-%H%M')
            ls -lrt 
            echo '###### Clonar el repositorio sa-bcm-content-ui ######'
            git clone -b jvelazquez https://${{secrets.GH_ACCESS_KEY}}@github.com/jeacor/sa-bcm-content-ui.git
            echo '###### Repositorio clonado ######'
            ls -lrt
            sleep 20
            echo '###### Detener y eliminar el Contenedor sa-bcm-content-ui ######'
            docker ps
            docker stop bcm-content-ui-container
            sleep 20
            docker rm bcm-content-ui-container
            echo '###### Eliminando la imagen... ######'
            docker images
            sleep 20
            docker rmi bcm-content-ui
            docker images
            echo '###### Ejecutando el Build y Deploy ######'
            cd  /home/GIT/sa-bcm-content-ui
            ls -lrt
            docker build -t bcm-content-ui .
            sleep 20
            docker run -d -p 5004:80 -v dataprotection-keys:/root/.aspnet/DataProtection-Keys --name  bcm-content-ui-container bcm-content-ui
            sleep 20
            echo '###### Contenedores corriendo ######'
            docker ps -a
            echo '###### fin del workflow ######'
